import { assetPath } from "@/lib/assetPath";

export type NavItem = {
  href: string;
  labelZh: string;
  labelEn: string;
};

export type SocialLink = {
  label: string;
  href: string;
};

export const siteConfig = {
  siteName: "Portfolio 2026",
  authorName: "陈子昂",
  authorNameEn: "Hayato",
  titleZh: "视觉设计师 / 插画师",
  titleEn: "Graphic Designer / Illustrator / Visual Designer",
  introZh: "聚焦儿童产品、视觉识别、插画与文创设计的阶段性作品整理。",
  introEn: "A curated archive of children's products, visual identity, illustration, and cultural creative design.",
  logo: {
    text: "PORTFOLIO",
    image: assetPath("/logo.svg"),
  },
  favicon: assetPath("/favicon.png?v=20260609"),
  faviconSvg: assetPath("/favicon.svg?v=20260609"),
  hero: {
    mainImage: assetPath("/assets/hero/hero-main.webp"),
    alt: "Chen Ziang Hayato visual design portfolio hero image",
    textLayers: {
      topLeft: assetPath("/assets/hero/text-top-left.png"),
      topRight: assetPath("/assets/hero/text-top-right.png"),
      bottomLeft: assetPath("/assets/hero/text-bottom-left.png"),
      bottomRight: assetPath("/assets/hero/text-bottom-right.png"),
    },
    marquee: {
      top: assetPath("/assets/marquee/top-marquee.webp"),
      bottom: assetPath("/assets/marquee/bottom-marquee.webp"),
    },
  },
  contact: {
    email: "q2860646087@gmail.com",
    phone: "19357391198",
    location: "浙江 / 杭州",
    wechat: "Chenziang21",
  },
  socialLinks: [
    { label: "Behance", href: "https://www.behance.net/your-handle" },
    { label: "Instagram", href: "https://www.instagram.com/your-handle" },
    { label: "小红书", href: "https://www.xiaohongshu.com/user/profile/your-id" },
    { label: "GitHub", href: "https://github.com/your-handle" },
  ] satisfies SocialLink[],
  navigation: [
    { href: "#about", labelZh: "关于", labelEn: "About" },
    { href: "#work", labelZh: "作品", labelEn: "Work" },
    { href: "#contact", labelZh: "联系", labelEn: "Contact" },
  ] satisfies NavItem[],
  footerTextZh: "© 2026 陈子昂。个人设计作品集。",
  footerTextEn: "Portfolio shell for selected design works.",
  notFoundTitle: "项目不存在",
  cover: {
    titleZh: "视觉设计作品集",
    titleEn: "Visual Design Portfolio",
    nameLabelZh: "个人视觉档案",
    nameLabelEn: "Personal Visual Archive",
    issueLabel: "No. 2026 / Vol. 01",
    stickerZh: "阶段整理 / 可编辑",
    stickerEn: "Selected Works",
    ctaZh: "开始浏览",
    ctaEn: "Scroll to Work",
    visual: {
      mainTitle: "PORTFOLIO",
      authorLine: "Chen Ziang / Hayato",
      noteTitle: "Visual Archive",
      noteBody: "Graphic Design / Illustration / Visual Identity",
      characterSlots: [
        {
          id: "hero-character-left",
          label: "Character",
          src: assetPath("/assets/characters/hero-character-left.svg"),
          placeholder: "角色插画整理中",
          position: "left",
        },
        {
          id: "hero-character-right",
          label: "Sticker",
          src: assetPath("/assets/characters/hero-character-right.svg"),
          placeholder: "贴纸视觉整理中",
          position: "right",
        },
      ],
    },
  },
  sections: {
    about: {
      titleZh: "关于我",
      titleEn: "Profile",
      eyebrowZh: "个人简介",
      eyebrowEn: "Profile",
      fileStickerEn: "File",
      contactTitleZh: "联系方式",
      contactTitleEn: "Contact",
      directionTitleZh: "设计方向",
      directionTitleEn: "Directions",
      educationTitleZh: "教育经历",
      educationTitleEn: "Education",
      workExperienceTitleZh: "工作经历",
      workExperienceTitleEn: "Work Experience",
      projectExperienceTitleZh: "项目经历",
      projectExperienceTitleEn: "Project Experience",
      designSkillsTitleZh: "设计技能",
      designSkillsTitleEn: "Design Skills",
      toolsTitleZh: "工具能力",
      toolsTitleEn: "Tools",
      aigcToolsTitleZh: "AIGC 工作流",
      aigcToolsTitleEn: "AIGC Workflow",
      objectiveTitleZh: "发展目标",
      objectiveTitleEn: "Objective",
      softSkillsTitleZh: "软性能力",
      softSkillsTitleEn: "Soft Skills",
      photoTitleZh: "设计师视觉卡片",
      photoTitleEn: "Visual Card",
    },
    work: {
      titleZh: "精选项目",
      titleEn: "Selected Projects",
      introZh: "每个项目以画册章节呈现，整理背景、灵感板、过程与最终应用展示。",
      introEn: "Each project is presented as a scrollable editorial chapter with research, process, and application notes.",
      yearLabelZh: "年份",
      yearLabelEn: "Year",
      categoryLabelZh: "分类",
      categoryLabelEn: "Category",
      categoryEnLabelZh: "英文分类",
      categoryEnLabelEn: "Category EN",
      moodboardLabelZh: "灵感板",
      moodboardLabelEn: "Moodboard",
      processLabelZh: "过程图",
      processLabelEn: "Process",
      finalLabelZh: "最终展示",
      finalLabelEn: "Final",
      detailButtonZh: "查看详情",
      detailButtonEn: "Case Study",
      backButtonZh: "返回作品",
      backButtonEn: "Back to Work",
      coverLabelZh: "项目主视觉",
      coverLabelEn: "Lead Visual",
      coverAltSuffixZh: "主视觉",
      processImagesTitleZh: "设计过程图片",
      processImagesTitleEn: "Process Images",
      finalImagesTitleZh: "关键视觉与应用展示",
      finalImagesTitleEn: "Final Visuals & Applications",
      toolsLabelZh: "工具",
      toolsLabelEn: "Tools",
      keywordsLabelZh: "关键词",
      keywordsLabelEn: "Keywords",
      briefLabelZh: "项目简述",
      briefLabelEn: "Brief",
      ideaLabelZh: "设计想法",
      ideaLabelEn: "Design Idea",
      typeLabelZh: "项目类型",
      typeLabelEn: "Project Type",
      imagePlaceholderZh: "作品内容整理中",
      imagePlaceholderEn: "Work Archive",
    },
    contact: {
      titleZh: "保持联系",
      titleEn: "Contact / The Last Page",
      introZh: "如果你想继续完善作品集、替换真实项目或开启新的视觉设计合作，可以从这里更新联系信息。",
      introEn: "Replace these links when you are ready to publish your portfolio or start a new collaboration.",
      endingZh: "谢谢翻阅，下一版作品集见。",
      endingEn: "Thanks for scrolling through this visual archive.",
    },
  },
  about: {
    bioZh:
      "关注品牌视觉、图形语言与视觉系统设计，作品围绕儿童视觉系统、IP 形象、图案设计与品牌识别展开，尝试将图形、色彩、版式与延展应用整合为具有识别度的设计系统。",
    bioEn:
      "Visual communication design / brand identity / children's visual system.",
    profileLine: "视觉传达设计 / 品牌视觉 / 儿童视觉系统",
    objective:
      "希望在品牌视觉、图案系统与儿童消费场景设计方向持续发展，建立兼具识别度、亲和力与落地能力的视觉作品。",
    profileContact: [
      { label: "TEL", value: "19357391198" },
      { label: "EMAIL", value: "q2860646087@gmail.com" },
      { label: "LOCATION", value: "浙江杭州" },
      { label: "WECHAT", value: "Chenziang21" },
    ],
    portrait: {
      src: assetPath("/profile/hayato-game-console.png"),
      alt: "陈子昂个人视觉信息卡",
      cardLabelZh: "VISUAL DESIGNER",
      placeholderZh: "儿童视觉 / 品牌识别 / 插画系统",
      placeholderEn: "CHILDREN'S VISUAL SYSTEM / BRAND IDENTITY / ILLUSTRATION",
    },
    designDirections: [
      { titleZh: "儿童视觉系统", titleEn: "Children's Visual System", icon: "01" },
      { titleZh: "图案与插画", titleEn: "Pattern & Illustration", icon: "02" },
      { titleZh: "品牌视觉识别", titleEn: "Brand Identity", icon: "03" },
      { titleZh: "包装与物料延展", titleEn: "Packaging & Touchpoints", icon: "04" },
    ],
    education: [
      {
        period: "2022.09 - 2026.06",
        titleZh: "浙江工商大学",
        titleEn: "视觉传达设计",
      },
    ],
    workExperience: [
      {
        period: "2025.12 - 2026.03",
        organizationZh: "正大（慈溪）现代农业建设有限公司",
        roleZh: "营销策划实习生",
        roleEn: "Marketing Planning Intern",
      },
      {
        period: "2025.06 - 2025.08",
        organizationZh: "上海新易腾集团有限公司",
        roleZh: "电商管培生",
        roleEn: "E-commerce Management Trainee",
      },
      {
        period: "2024.04 - 2024.07",
        organizationZh: "杭州智能向量文化科技有限公司",
        roleZh: "品牌设计实习生",
        roleEn: "Brand Design Intern",
      },
    ],
    projectExperience: [
      {
        index: "01",
        titleZh: "儿童服装图案视觉系统设计",
        titleEn: "Children's Apparel Pattern Visual System",
      },
      {
        index: "02",
        titleZh: "儿童护眼 IP 视觉系统设计",
        titleEn: "Children's Eyecare IP Visual System",
      },
      {
        index: "03",
        titleZh: "品牌视觉识别系统设计实践",
        titleEn: "Brand Identity Design Practice",
      },
    ],
    designSkills: ["品牌视觉设计", "版式设计", "图形设计", "图案系统设计", "IP 视觉延展", "包装与物料延展", "视觉系统整理"],
    tools: [
      { name: "Photoshop", icon: assetPath("/assets/icons/software/photoshop.png") },
      { name: "Illustrator", icon: assetPath("/assets/icons/software/illustrator.png") },
      { name: "InDesign", icon: assetPath("/assets/icons/software/indesign.png") },
      { name: "Procreate", icon: assetPath("/assets/icons/software/procreate.png") },
    ],
    aigcTools: ["ChatGPT", "Codex", "Midjourney", "即梦 AI", "Image2Image", "LLM 协作", "多模态生成", "AI Agent", "Vibe Coding"],
    softSkills: ["信息整理", "视觉表达", "项目执行", "内容策划", "沟通协作", "审美判断", "学习能力"],
  },
};
