export type NavItem = {
  href: string;
  labelZh: string;
  labelEn: string;
};

export type SocialLink = {
  label: string;
  href: string;
};

export const siteConfig = {
  siteName: "Portfolio 2026",
  authorName: "陈子昂",
  authorNameEn: "Hayato",
  titleZh: "视觉设计师 / 插画师",
  titleEn: "Graphic Designer / Illustrator / Visual Designer",
  introZh: "聚焦儿童产品、视觉识别、插画与文创设计的阶段性作品整理。",
  introEn: "A curated archive of children's products, visual identity, illustration, and cultural creative design.",
  logo: {
    text: "PORTFOLIO",
    image: "/logo.svg",
  },
  favicon: "/favicon.png?v=20260609",
  hero: {
    mainImage: "/assets/hero/hero-main.png",
    alt: "Chen Ziang Hayato visual design portfolio hero image",
    textLayers: {
      topLeft: "/assets/hero/text-top-left.png",
      topRight: "/assets/hero/text-top-right.png",
      bottomLeft: "/assets/hero/text-bottom-left.png",
      bottomRight: "/assets/hero/text-bottom-right.png",
    },
    marquee: {
      top: "/assets/marquee/top-marquee.png",
      bottom: "/assets/marquee/bottom-marquee.png",
    },
  },
  contact: {
    email: "q2860646087@gmail.com",
    phone: "19357391198",
    location: "浙江 / 杭州",
    wechat: "Chenziang21",
  },
  socialLinks: [
    { label: "Behance", href: "https://www.behance.net/your-handle" },
    { label: "Instagram", href: "https://www.instagram.com/your-handle" },
    { label: "小红书", href: "https://www.xiaohongshu.com/user/profile/your-id" },
    { label: "GitHub", href: "https://github.com/your-handle" },
  ] satisfies SocialLink[],
  navigation: [
    { href: "#about", labelZh: "关于", labelEn: "About" },
    { href: "#work", labelZh: "作品", labelEn: "Work" },
    { href: "#contact", labelZh: "联系", labelEn: "Contact" },
  ] satisfies NavItem[],
  footerTextZh: "© 2026 陈子昂。个人设计作品集。",
  footerTextEn: "Portfolio shell for selected design works.",
  notFoundTitle: "项目不存在",
  cover: {
    titleZh: "视觉设计作品集",
    titleEn: "Visual Design Portfolio",
    nameLabelZh: "个人视觉档案",
    nameLabelEn: "Personal Visual Archive",
    issueLabel: "No. 2026 / Vol. 01",
    stickerZh: "阶段整理 / 可编辑",
    stickerEn: "Selected Works",
    ctaZh: "开始浏览",
    ctaEn: "Scroll to Work",
    visual: {
      mainTitle: "PORTFOLIO",
      authorLine: "Chen Ziang / Hayato",
      noteTitle: "Visual Archive",
      noteBody: "Graphic Design / Illustration / Visual Identity",
      characterSlots: [
        {
          id: "hero-character-left",
          label: "Character",
          src: "/assets/characters/hero-character-left.svg",
          placeholder: "CHARACTER PLACEHOLDER",
          position: "left",
        },
        {
          id: "hero-character-right",
          label: "Sticker",
          src: "/assets/characters/hero-character-right.svg",
          placeholder: "STICKER PLACEHOLDER",
          position: "right",
        },
      ],
    },
  },
  sections: {
    about: {
      titleZh: "关于我",
      titleEn: "About Me",
      eyebrowZh: "关于我",
      eyebrowEn: "Designer File",
      fileStickerEn: "File",
      contactTitleZh: "联系方式",
      contactTitleEn: "Contact",
      directionTitleZh: "设计方向",
      directionTitleEn: "Directions",
      educationTitleZh: "教育经历",
      educationTitleEn: "Education",
      skillsTitleZh: "软件技能",
      skillsTitleEn: "Tools",
      experienceTitleZh: "工作 / 项目经历",
      experienceTitleEn: "Experience",
      awardsTitleZh: "获奖经历",
      awardsTitleEn: "Achievement",
      hobbiesTitleZh: "兴趣爱好",
      hobbiesTitleEn: "Interests",
      keywordsTitleZh: "设计关键词",
      keywordsTitleEn: "Keywords",
      photoTitleZh: "照片占位",
      photoTitleEn: "Your Photo",
    },
    work: {
      titleZh: "精选项目",
      titleEn: "Selected Projects",
      introZh: "每个项目以画册章节呈现，保留背景、灵感板、过程与最终展示的位置。",
      introEn: "Each project is presented as a scrollable editorial chapter with editable placeholders.",
      yearLabelZh: "年份",
      yearLabelEn: "Year",
      categoryLabelZh: "分类",
      categoryLabelEn: "Category",
      categoryEnLabelZh: "英文分类",
      categoryEnLabelEn: "Category EN",
      moodboardLabelZh: "灵感板",
      moodboardLabelEn: "Moodboard",
      processLabelZh: "过程图",
      processLabelEn: "Process",
      finalLabelZh: "最终展示",
      finalLabelEn: "Final",
      detailButtonZh: "查看详情",
      detailButtonEn: "Case Study",
      backButtonZh: "返回作品",
      backButtonEn: "Back to Work",
      coverLabelZh: "项目封面",
      coverLabelEn: "Cover",
      coverAltSuffixZh: "封面",
      processImagesTitleZh: "设计过程图片",
      processImagesTitleEn: "Process Images",
      finalImagesTitleZh: "关键视觉与应用展示",
      finalImagesTitleEn: "Final Visuals & Applications",
      toolsLabelZh: "工具",
      toolsLabelEn: "Tools",
      keywordsLabelZh: "关键词",
      keywordsLabelEn: "Keywords",
      briefLabelZh: "项目简述",
      briefLabelEn: "Brief",
      ideaLabelZh: "设计想法",
      ideaLabelEn: "Design Idea",
      typeLabelZh: "项目类型",
      typeLabelEn: "Project Type",
      imagePlaceholderZh: "图片占位",
      imagePlaceholderEn: "Image Placeholder",
    },
    contact: {
      titleZh: "保持联系",
      titleEn: "Contact / The Last Page",
      introZh: "如果你想继续完善作品集、替换真实项目或开启新的视觉设计合作，可以从这里更新联系信息。",
      introEn: "Replace these links when you are ready to publish your portfolio or start a new collaboration.",
      endingZh: "谢谢翻阅，下一版作品集见。",
      endingEn: "Thanks for scrolling through this visual archive.",
    },
  },
  about: {
    bioZh:
      "视觉设计师，热爱用图形和色彩讲故事。关注儿童产品、自然与文化，擅长将创意与社会价值结合，打造有温度的设计作品。",
    bioEn:
      "Visual designer who loves telling stories with graphics and colors. Focus on children's products, nature and culture, combining creativity with social value.",
    portrait: {
      src: "/assets/about/profile.png",
      alt: "陈子昂个人照片",
      placeholderZh: "照片占位",
      placeholderEn: "Your Photo",
    },
    designDirections: [
      { titleZh: "儿童产品设计", titleEn: "Children's Product Design", icon: "01" },
      { titleZh: "插画设计", titleEn: "Illustration Design", icon: "02" },
      { titleZh: "视觉识别设计", titleEn: "Visual Identity Design", icon: "03" },
      { titleZh: "文创产品设计", titleEn: "Cultural & Creative Design", icon: "04" },
    ],
    education: [
      {
        period: "浙江工商大学",
        titleZh: "设计相关专业",
        titleEn: "Design-related Program",
      },
    ],
    softwareSkills: [
      { name: "Illustrator", icon: "Ai", src: "/assets/icons/illustrator.svg" },
      { name: "Photoshop", icon: "Ps", src: "/assets/icons/photoshop.svg" },
      { name: "Procreate", icon: "Pr", src: "/assets/icons/procreate.svg" },
      { name: "Figma", icon: "Fg", src: "/assets/icons/figma.svg" },
    ],
    experience: [
      { period: "2023 - 至今", titleZh: "自由设计师", titleEn: "Freelance Designer" },
      { period: "2022 - 2023", titleZh: "儿童品牌设计项目", titleEn: "Children's Brand Design Project" },
      { period: "2021 - 2022", titleZh: "视觉设计实习", titleEn: "Visual Design Intern" },
    ],
    awards: [
      { period: "2025", titleZh: "学生科学研究项目奖项", titleEn: "Student Research Project Award" },
      { period: "2025", titleZh: "字体设计大赛优秀奖", titleEn: "Typography Design Award" },
      { period: "2024", titleZh: "创意设计大赛入围奖", titleEn: "Creative Design Competition Shortlist" },
    ],
    contactMethods: [
      { labelZh: "电话", labelEn: "Phone", value: "19357391198", icon: "PH" },
      { labelZh: "邮箱", labelEn: "Mail", value: "q2860646087@gmail.com", icon: "MA" },
      { labelZh: "微信", labelEn: "WeChat", value: "Chenziang21", icon: "WX" },
      { labelZh: "住址", labelEn: "Address", value: "浙江 / 杭州", icon: "AD" },
    ],
    hobbies: ["插画收集", "儿童产品观察", "手账拼贴", "视觉档案整理"],
    keywords: ["儿童友好", "图案系统", "视觉识别", "文创延展", "插画叙事", "作品集编辑"],
  },
};
